const ADD_TODO = "ADD_TODO";
const DELETE_TODO = "DELETE_TODO";
const UPDATE_TODO = "UPDATE_TODO";

const CHANGE_INPUT = "CHANGE_INPUT";

export {
    ADD_TODO,
    DELETE_TODO,
    UPDATE_TODO,

    CHANGE_INPUT
};